Add 2 extra columns to o-footer, one for Community Events and More from FT
Financial-Times/o-footer pull request #174
Opened 2021-06-25 14:38 UTC by ahmadmoawad

- Add 2 extra columns to o-footer, one for Community Events and More from FT
- Convert More from FT to column
- Allow accordion for small screen

Jira: https://financialtimes.atlassian.net/browse/HIVE-150

2021-06-25 14:53 UTC, maxcbc commented on demos/src/footer.mustache
> +					<h3 class="o-footer__matrix-title last__static-link" aria-controls="o-footer-section-5" aria-hidden="false">
The classname `last__static-link` should be a modifier class on `o-footer__matrix-title` such as `o-footer__matrix-title--external-link`.

2021-06-25 14:54 UTC, maxcbc commented on demos/src/footer.mustache
> +					<h3 class="o-footer__matrix-title last__static-link" aria-controls="o-footer-section-5" aria-hidden="false">
Removal of the `aria-controls` should prevent this item being collapsed on smaller screen sizes. Removing the need for the `:not` in the scss

2021-06-25 14:56 UTC, maxcbc commented
You should also update the example code in README.md too. So people are aware of the new html structure needed.

2021-06-25 14:59 UTC, maxcbc commented
It'd be nice to add a screenshot, 'before' and 'after' this PR to make the differences clear. Given the differences at both wide and smaller screens, its worth doing a before and after for each.

2021-06-29 10:15 UTC, notlee requested changes
Thanks for the PR!

1. Question: Because this requires markup changes we'll need to release a major version, which requires teams to update their projects. o-footer is used by many teams/projects. Is there a rollout plan in place? If not, we can help.

2. It looks like the `focus` state of the title link is obscured by the `overflow: hidden` set on `.o-footer__matrix-title` and `.o-footer__matrix-link`, which is used to achieve the ellipse effect. That's an accessibility issue for our users who navigate using the keyboard, it's easy to lose your place. I'm not sure what the best solution is 🤔

https://user-images.githubusercontent.com/10405691/123778870-794c4600-d8c9-11eb-895a-ebf739cee04a.mp4

For (2) I would be tempted to introduce a new `span` element inside the anchor `a` links, and move the overflow/ellipse properties from the `a` links to the the new child `span` element. 
```html
<a class ='o-footer__matrix-link' href="#">
    <span class="o-footer__matrix-link__copy">
        copy with overflow / elispies    
    </span>
</a>
```
That way the overflow won't obscure the focus state of the link. And bonus! That approach would allow us to have the left chevron `>` in the link after the ellipses, as in the design (currently the ellipses hides the chevron).
![Screenshot 2021-06-29 at 11 07 38](https://user-images.githubusercontent.com/10405691/123779783-7140d600-d8ca-11eb-86a5-8fc1a98a5550.png)
![Screenshot 2021-06-29 at 11 07 21](https://user-images.githubusercontent.com/10405691/123779785-71d96c80-d8ca-11eb-947a-9f8c7d7cba71.png)
There might be a better approach though, it'd be nice to avoid extra markup, what do you think? Let me know if you'd like to pair on it :)

2021-06-29 11:46 UTC, ahmadmoawad commented on src/scss/_mixins.scss
> +				border-top: '';
HI @notlee ,

Actually the Figma design not showing any border above the link. I will share it with you.

Thanks

2021-06-29 12:29 UTC, ahmadmoawad commented on src/scss/_mixins.scss
> +				border-top: '';
@notlee The code has been updated

2021-07-01 13:47 UTC, notlee commented
Just force pushed a rebase as we've released v8 since the start of this PR :)

2021-07-02 16:45 UTC, notlee commented
See https://github.com/Financial-Times/o-footer/pull/174

2021-07-02 16:46 UTC, notlee approved these changes

2021-07-02 16:47 UTC, notlee commented
Next steps:
- Release v9.0.0
- Backport these changes to v7.0.0 and release as `v9.0.0-bower`

2021-07-07 14:33 UTC, merged

2021-07-07 14:35 UTC, origamiserviceuser commented
:tada: This PR is included in version v9.0.0 :tada: